trigger: none

pr: none

parameters:
- name: subscriptionQuotaIdWhitelistParameters
  type: object
  default:
    - undefined

variables:
  ServiceConnection: AzADServicePrincipalInsights
  SubscriptionQuotaIdWhitelist: ${{ join(',',parameters.subscriptionQuotaIdWhitelistParameters) }}
  WikiDir: wiki
  CsvDelimiter: ;
  ScriptDir: pwsh
  Script: AzADServicePrincipalInsights.ps1

schedules:
- cron: "0 6,16 * * *"
  displayName: at 6am, 4pm
  always: true
  branches:
    include:
    - master

jobs:
- job: AzADServicePrincipalInsights  
  timeoutInMinutes: 0

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)/$(ScriptDir)/prerequisites.ps1
    displayName: 'Prerequisites check'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - task: AzurePowerShell@4
    inputs:
      azureSubscription: '$(ServiceConnection)'
      scriptType: filePath
      pwsh: true
      scriptPath: '$(System.DefaultWorkingDirectory)/$(ScriptDir)/$(Script)'
      scriptArguments: '-OutputPath $(WikiDir) -AzureDevOpsWikiAsCode -ThrottleLimit 10 -ThrottleLimitGraph 10'
      azurePowerShellVersion: latestVersion
    displayName: 'Run AzADServicePrincipalInsights v1'
  - powershell: |
      write-host "#################################"
      write-host "Push AzADServicePrincipalInsights output to repository"
      write-host "#################################"
      $executionDateTimeInternationalReadable = get-date -format "dd-MMM-yyyy HH:mm:ss"
      $currentTimeZone = (Get-TimeZone).Id
      git config --global user.email "AzADServicePrincipalInsightsPipeline@azdo.com"
      $PipelineInfo = "Pipeline: '$(Build.DefinitionName)' 'rev $(Build.BuildNumber)' (Project: $([uri]::EscapeDataString("$(System.TeamProject)")); Repository: $(Build.Repository.Name); Branch: $(Build.SourceBranchName) Commit: $(Build.SourceVersion))"
      git config --global user.name "$PipelineInfo"
      git config pull.rebase false
      git add --all
      git commit -m "wiki $executionDateTimeInternationalReadable ($currentTimeZone)"
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin HEAD:$(Build.SourceBranchName)
    displayName: 'Push AzADServicePrincipalInsights v1 output to repository'
