#change line 8 accordingly
#if you want to leverage parameters, add them in line 53

name: AzADServicePrincipalInsights

env:
  OutputPath: wiki
  ManagementGroups_s: managementGroupId #example multiple ManagementGroups: 'mgId0,mgId1'
  ScriptDir: pwsh #example: 'my folder\pwsh' or 'my folder/pwsh'
  ScriptPrereqFile: prerequisites.ps1
  ScriptFile: AzADServicePrincipalInsights.ps1

on:
  #schedule:
  #  - cron:  '45 4,16 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  AzADServicePrincipalInsights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.CREDS}}
          enable-AzPSSession: true
          # CREDS looks like this:
          # {
          #   "tenantId": "<GUID>",
          #   "subscriptionId": "<GUID>",
          #   "clientId": "<GUID>",
          #   "clientSecret": "<GUID>"
          # }

      - name: Check prerequisites
        uses: azure/powershell@v1
        with:
          inlineScript: |
            . .\$($env:ScriptDir)\$($env:ScriptPrereqFile) -OutputPath ${env:OutputPath}
          azPSVersion: "latest"

      - name: Run AzADServicePrincipalInsights
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $ManagementGroupId = (${env:ManagementGroups_s}).split(',')
            . .\$($env:ScriptDir)\$($env:ScriptFile) -ScriptPath ${env:ScriptDir} -OutputPath ${env:OutputPath} -ManagementGroupId $ManagementGroupId
          azPSVersion: "latest"

      - name: Push AzADServicePrincipalInsights output to repository
        run: |
          git config --global user.email "AzADServicePrincipalInsightsGHActions@ghActions.com"
          git config --global user.name "$GITHUB_ACTOR"
          git config pull.rebase false
          git add --all
          git commit -m "$GITHUB_WORKFLOW $GITHUB_JOB"
          git push